apiVersion: v1
kind: Service
metadata:
  name: clickhouse-option2-external
  namespace: clickhouse
spec:
  type: LoadBalancer
  ports:
  - port: 8123
    targetPort: 8123
    protocol: TCP
    name: http
  selector:
    app: clickhouse-option2
