apiVersion: v1
kind: Service
metadata:
  name: clickhouse-option1
  namespace: clickhouse
  labels:
    app: clickhouse-option1
    option: "1"
spec:
  type: ClusterIP
  ports:
  - port: 8123
    targetPort: 8123
    protocol: TCP
    name: http
  - port: 9000
    targetPort: 9000
    protocol: TCP
    name: native
  selector:
    app: clickhouse-option1
