apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: clickhouse
data:
  collector.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    processors:
      batch:
        timeout: 10s
        send_batch_size: 1024

      # Add resource attributes
      resource:
        attributes:
          - key: collector.name
            value: otel-collector
            action: insert
          - key: k8s.pod.name
            value: ${POD_NAME}
            action: upsert

    exporters:
      # File exporter to write JSON to local disk
      awss3:
        s3uploader:
          region: 'us-east-1'  # Update to your region
          s3_bucket: 'clickhouse-demo-metrics-np-2025'
          s3_prefix: 'raw/'
          s3_partition: 'hour'
          file_prefix: 'metrics-'
        marshaler: otlp_json

      # Logging exporter for debugging
      logging:
        verbosity: normal
        sampling_initial: 5
        sampling_thereafter: 200

    service:
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [batch, resource]
          exporters: [awss3]
  